# Generated by Django 4.1.2 on 2022-11-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oyappanmaar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8)),
            ],
        ),
    ]
