# Generated by Django 4.1.2 on 2022-11-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oyappanmaar', '0002_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('notes', models.CharField(max_length=100)),
                ('l', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NotePublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('notes', models.CharField(max_length=32)),
                ('l', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='allowed',
            old_name='username',
            new_name='roll',
        ),
        migrations.RenameField(
            model_name='credentials',
            old_name='name',
            new_name='person',
        ),
    ]
